services:
  app:
    image: registry.gitlab.4itec.ddns.net/frank-k/4isafecross:latest-amd64
    container_name: 4isafecross
    restart: unless-stopped
    tty: true
    stdin_open: true

    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=Europe/Paris

    devices:
      - /dev/dri:/dev/dri

    ports:
      - "5000:5000"

    volumes:
      - /data/4isafecross:/app/data
      - ./config:/app/config

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:5050/health')"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3