[logging]
level = INFO

[TELEGRAM]
TOKEN = 6741846240:AAGe2Mcw4sbTmuOCHhN1xJ07Onf9TrSv_fo
CHAT_ID = -4115471727

[APP]
MOTIONTRESHOLD = 10000
APP_NAME = 4iSafeCross
APP_VERSION = 0.1.1
INF_THRESHOLD = 0.4
DB_PATH = db/detections.db
DETECTION = extended

# Paramètres d'inférence
FONCTION = /predict_frame_rf_detr/
URL = http://127.0.0.1:8003/

[RTSP]
LOGIN = admin
PASSWORD = 4iTec2025!
HOST = ["192.168.2.156", "192.168.2.157"]
PORT = 554
STREAM = stream1
