[logging]
# Niveau de log : DEBUG, INFO, WARNING, ERROR, CRITICAL
level = DEBUG

[TELEGRAM]
# Token du bot Telegram pour les notifications
TOKEN = 6741846240:AAGe2Mcw4sbTmuOCHhN1xJ07Onf9TrSv_fo
# ID du chat Telegram pour recevoir les alertes
CHAT_ID = -4115471727

[APP]
# Seuil de pixels blancs pour la détection de mouvement
MOTIONTHRESHOLD = 10000
# Nom de l'application
APP_NAME = 4iSafeCross
# Version de l'application
APP_VERSION = 0.1.1
# Seuil de confiance pour l'inférence
INF_THRESHOLD = 0.7
# Chemin vers la base de données des détections
DB_PATH = db/detections.db
# Mode de détection : simple ou extended ou transfert
DETECTION = transfert
# Classes utilisées pour chaque mode de détection (format liste Python)
EXTENDED_CLASSES = [1, 3, 6, 7, 8]
TRANSFERT_CLASSES = [0, 1, 2, 3, 4, 5]
SIMPLE_CLASSES = [1 , 2]
# Temps d'attente avant test RTSP (en secondes)
WAIT_BEFORE_TEST_RTSP = 3
# Paramètres d'inférence /predict_frame_rf_detr/ or /predict_frame/
FONCTION_RFDETR = /predict_frame_rf_detr/
URL_RFDETR = http://127.0.0.1:8002/
# for predict_frame/
FONCTION_YOLO = /predict_frame/
URL_YOLO = http://127.0.0.1:8004/


[RTSP]
# Identifiants pour les caméras RTSP
LOGIN = admin
PASSWORD = 4iTec2025!
# Liste des adresses IP des caméras (format liste Python)
HOST = ["192.168.2.156", "192.168.2.157"]
# Port RTSP
PORT = 554
# Nom du stream
STREAM = stream1

[STATURE_COLORS]
# Couleurs pour les différentes statures de personnes détectées (format RGB)
# debout : Personne debout (vert)
debout = (0, 255, 0)
# assis : Personne assise (rouge)
assis = (255, 0, 0)
# marchant : Personne en marche (cyan)
marchant = (0, 255, 255)
# jambes_masquees : Jambes masquées/ocultées (magenta)
jambes_masquees = (255, 0, 255)
# inconnu : Stature inconnue (bleu)
inconnu = (0, 0, 255)
# conducteur : Conducteur de véhicule (orange)
conducteur = (255, 165, 0)
# pieton : Piéton (violet)
pieton = (128, 0, 128)

[OBJECT_COLORS]
# Couleurs pour les différents types d'objets détectés (format RGB)
person = (0, 255, 0)  # Vert
forklift = (255, 0, 0) # Rouge
driver = (0, 0, 255) # Bleu
unknown = (255, 255, 0) # Jaune