# Positions des projecteurs relais sur le plan caméra
# Généré automatiquement par l'éditeur de zones
# Format : [relay{id}_cam{cam_id}]  x = <pixels réels>  y = <pixels réels>
[relay0_cam0]
x = 191
y = 761

[relay1_cam0]
x = 1398
y = 436

[relay2_cam0]
x = 946
y = 91